//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BicycleTheftApp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BicycleTheftApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   福島県伊達市梁川町字中町
        ///福島県伊達市梁川町字南本町
        ///福島県伊達市梁川町青葉町
        ///福島県伊達市保原町字四丁目
        ///福島県伊達市川原町
        ///福島県伊達市細谷
        ///福島県福島市御山町
        ///福島県福島市狐塚
        ///福島県福島市新町
        ///福島県福島市天神町
        ///福島県福島市森合町
        ///福島県福島市笹木野字北中谷地
        ///福島県福島市笹木野字金谷東
        ///福島県福島市八島田字琵琶渕
        ///福島県福島市黒岩字堂ノ後
        ///福島県福島市黒岩字中沖
        ///福島県福島市太平寺字児子塚
        ///福島県福島市太平寺字毘沙門堂
        ///福島県福島市永井川字壇ノ腰
        ///福島県福島市伏拝字清水内
        ///福島県福島市伏拝字田中
        ///福島県福島市方木田字葉ノ木立
        ///福島県福島市下鳥渡字八幡塚
        ///福島県福島市方木田字仲田
        ///福島県川俣町大字鶴沢字学校前
        ///福島県福島市松川町字中原
        ///福島県福島市松川町字原
        ///福島県福島市松川町関谷字坂下
        ///福島県福島市渡利字中江町
        ///福島県福島市渡利字平ケ森
        ///福島県福島市泉字大仏
        ///福島県福島市泉字早稲田
        ///福島県福島市南沢又字上並松
        ///福島県福島市南沢又字下並松
        ///福島県福島市入江町
        ///福島県福島市春日町
        ///福島県福島市上浜町
        ///福島県福島市五老内町
        ///福島 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string locationinfo {
            get {
                return ResourceManager.GetString("locationinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   37.85463794963177, 140.60631031124217
        ///37.85554783796101, 140.59996033083482
        ///37.84582040838182, 140.60125802032985
        ///37.818157418480546, 140.55216249674274
        ///37.812781757977014, 140.4963064011806
        ///37.82458960549872, 140.4949656017486
        ///37.764393492755964, 140.4672365413844
        ///37.7660870963853, 140.46562870347407
        ///37.75693950418707, 140.46732848335392
        ///37.760316567521684, 140.4630595438578
        ///37.764060005143605, 140.4623578661843
        ///37.766354791184426, 140.43413500474145
        ///37.76575271056567, 140.42464671995018
        ///37.76 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1
        ///1
        ///2
        ///1
        ///1
        ///10
        ///3
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///17
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///2
        ///4
        ///1
        ///1
        ///1
        ///2
        ///2
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///21
        ///1
        ///1
        ///1
        ///2
        ///1
        ///2
        ///1
        ///21
        ///1
        ///2
        ///1
        ///3
        ///1
        ///1
        ///1
        ///1
        ///1
        ///27
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///3
        ///4
        ///1
        ///1
        ///2
        ///1
        ///1
        ///1
        ///1
        ///1
        ///3
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///2
        ///1
        ///1
        ///1
        ///1
        ///1
        ///29
        ///1
        ///1
        ///1
        ///1
        ///4
        ///1
        ///2
        ///1
        ///1
        ///1
        ///1
        ///3
        ///1
        ///1
        ///1
        ///1
        ///1
        ///11
        ///1
        ///3
        ///1
        ///7
        ///1
        ///1
        ///4
        ///1
        ///1
        ///1
        ///17
        ///1
        ///1
        ///1
        ///1
        ///1
        ///3
        ///1
        ///4
        ///8
        ///1
        ///1
        ///1
        ///3
        ///1
        ///14
        ///6
        ///1
        ///1
        ///2
        ///1
        ///1
        ///1
        ///1
        ///5
        ///3
        ///1
        ///1
        ///2
        ///2
        ///1
        ///2
        ///1
        ///2
        ///9
        ///1
        ///2
        ///1
        ///3
        ///1
        ///2
        ///1
        ///1
        ///2
        ///1
        ///1
        ///1
        ///1
        ///1
        ///2
        ///1
        ///2
        ///1        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string theftinfo {
            get {
                return ResourceManager.GetString("theftinfo", resourceCulture);
            }
        }
    }
}
